title: Stimulsoft Reports Documentation
description:
baseurl: "/Stimulsoft.Server.API.Manual"
url: "https://stimulsoft.github.io"
sidebar_title: "Stimulsoft Server"
exclude_from_menu: ["Out_Of_Date", "Extra_Text", "Stimulsoft Cloud"]

plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter

relative_links:
  enabled: true
  collections: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
      render_with_liquid: false

exclude:
  - scripts/
  - "*.py"
  - README.md
  - ARCHITECTURE.md
  - Gemfile
  - Gemfile.lock
